# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import cv2
  
  
# define a video capture object
vid = cv2.VideoCapture(0)

class Ui_EGYPark(object):
    def setupUi(self, EGYPark):
        EGYPark.setObjectName("EGYPark")
        EGYPark.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(EGYPark)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 30, 311, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 80, 301, 41))
        self.label_2.setObjectName("label_2")
        self.img_lable = QtWidgets.QLabel(self.centralwidget)
        self.img_lable.setGeometry(QtCore.QRect(20, 10, 311, 411))
        self.img_lable.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.img_lable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.img_lable.setLineWidth(5)
        self.img_lable.setText("")
        self.img_lable.setObjectName("img_lable")
        EGYPark.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EGYPark)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        EGYPark.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EGYPark)
        self.statusbar.setObjectName("statusbar")
        EGYPark.setStatusBar(self.statusbar)

        self.retranslateUi(EGYPark)
        QtCore.QMetaObject.connectSlotsByName(EGYPark)

    def retranslateUi(self, EGYPark):
        _translate = QtCore.QCoreApplication.translate
        EGYPark.setWindowTitle(_translate("EGYPark", "EGY Park"))
        self.label.setText(_translate("EGYPark", "TextLabel"))
        self.label_2.setText(_translate("EGYPark", "TextLabel"))

vid.release()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EGYPark = QtWidgets.QMainWindow()
    ui = Ui_EGYPark()
    ui.setupUi(EGYPark)
    EGYPark.show()
    sys.exit(app.exec())
